/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package v1alpha1

import (
	"time"

	flaggerv1 "github.com/fluxcd/flagger/pkg/apis/flagger/v1beta1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// MultiClusterCanarySpec defines the desired state of MultiClusterCanary
type MultiClusterCanarySpec struct {
	// GitopsClusterSelector is a label selector for matching against
	// target clusters.
	// +required
	GitopsClusterSelector metav1.LabelSelector `json:"gitopsClusterSelector"`

	// +optional
	CanaryNamespace string `json:"canaryNamespace,omitempty"`

	// TargetRef references a target resource.
	// +required
	TargetRef flaggerv1.LocalObjectReference `json:"targetRef"`

	// +required
	Interval metav1.Duration `json:"interval"`

	// AutoscalerRef references an autoscaling resource
	// +optional
	AutoscalerRef *flaggerv1.AutoscalerRefernce `json:"autoscalerRef,omitempty"`

	// Reference to NGINX ingress resource
	// +optional
	IngressRef *flaggerv1.LocalObjectReference `json:"ingressRef,omitempty"`

	// Reference to APISIX route resource
	// +optional
	RouteRef *flaggerv1.LocalObjectReference `json:"routeRef,omitempty"`

	// Reference to Gloo Upstream resource. Upstream config is copied from
	// the referenced upstream to the upstreams generated by flagger.
	// +optional
	UpstreamRef *flaggerv1.CrossNamespaceObjectReference `json:"upstreamRef,omitempty"`

	// Service is the Service configuration for all Canaries.
	// +required
	Service MultiClusterCanaryService `json:"service"`

	// Analysis is the analysis configuration for all Canaries.
	// +required
	Analysis MultiClusterCanaryAnalysis `json:"analysis"`

	// Timeout is the duration to wait for until all Canaries report themselves
	// to be in a state where they can start shifting traffic and begin the analysis.
	// If nil, we wait forever until the Canaries are ready.
	// +optional
	Timeout *metav1.Duration `json:"timeout,omitempty"`

	// PromotionStrategy is the strategy to be used for promotion/rollback.
	// +required
	PromotionStrategy PromotionStrategy `json:"promotionStrategy"`
}

type MultiClusterCanaryService struct {
	// The default Service configuration for all Canaries.
	// +required
	flaggerv1.CanaryService `json:",inline"`

	// Overrides is a list of Service configs used for overriding
	// Service creation on specific clusters.
	// +optional
	Overrides []MultiClusterCanaryServiceOverride `json:"overrides,omitempty"`
}

type MultiClusterCanaryServiceOverride struct {
	// GitopsClusterSelector is a label selector for matching
	// against GitopsCluster objects.
	// +required
	GitopsClusterSelector metav1.LabelSelector `json:"gitopsClusterSelector"`

	// The Service config override to be used for the matchd clusters.
	// +required
	Service flaggerv1.CanaryService `json:"service"`
}

type MultiClusterCanaryAnalysis struct {
	// The default Service configuration for all Canaries.
	// +required
	flaggerv1.CanaryAnalysis `json:",inline"`

	// Overrides is a list of analysis configs used for overriding
	// Canary analysis on specific clusters.
	// +optional
	Overrides []MultiClusterCanaryAnalysisOverride `json:"overrides,omitempty"`
}

type MultiClusterCanaryAnalysisOverride struct {
	// GitopsClusterSelector is a label selector for matching
	// against GitopsCluster objects.
	// +required
	GitopsClusterSelector metav1.LabelSelector `json:"gitopsClusterSelector"`

	// The Service config override to be used for the matchd clusters.
	// +required
	Analysis flaggerv1.CanaryAnalysis `json:"analysis"`
}

type PromotionStrategy struct {
	// The type of promotion/rollback strategy.
	// +kubebuilder:validation:Enum=pragmatic;strict;permissive
	// +required
	Type string `json:"type"`
	// FailedRetriesThreshold is the no. of faild retries to tolerate
	// after doing a full rollback of all the Canaries.
	// Used only if Type is "pragmatic". Defaults to 3.
	// +optional
	FailedRetriesThreshold *int `json:"failedRetriesThreshold,omitempty"`
}

// MultiClusterCanaryStatus defines the observed state of MultiClusterCanary
type MultiClusterCanaryStatus struct {
	Inevntory []CanaryObjRef          `json:"inventory,omitempty"`
	Phase     MultiClusterCanaryPhase `json:"phase,omitempty"`
}

type CanaryObjRef struct {
	ClusterName      string      `json:"cluster"`
	ClusterNamespace string      `json:"clusterNamespace"`
	Name             string      `json:"name"`
	Namespace        string      `json:"namespace"`
	State            CanaryState `json:"state"`
	Retries          int         `json:"retries"`
}

type MultiClusterCanaryPhase string

type CanaryState string

const (
	RolloutApproved CanaryState = "RolloutApproved"
	// Progressing       CanaryState = "Progressing"
	PromotionApproved CanaryState = "PromotionApproved"
	// Promoted          CanaryState = "Promoted"
	Retrying  CanaryState = "Retrying"
	Succeeded CanaryState = "Succeeded"
	Failed    CanaryState = "Failed"
)

const (
	PendingRolloutApproval   MultiClusterCanaryPhase = "PendingRolloutApproval"
	WaitingProgress          MultiClusterCanaryPhase = "WaitingProgress"
	Progressing              MultiClusterCanaryPhase = "Progressing"
	PendingPromotionApproval MultiClusterCanaryPhase = "PendingPromotionApproval"
	WaitingPromotion         MultiClusterCanaryPhase = "WaitingPromotion"
	Promoted                 MultiClusterCanaryPhase = "Promoted"
	PendingRollback          MultiClusterCanaryPhase = "PendingRollback"
	RolledBack               MultiClusterCanaryPhase = "RolledBack"
)

type CanaryWebhookState struct {
	ConfirmRollout   bool `json:"confirmRollout,omitempty"`
	ConfirmPromotion bool `json:"confirmPromotion,omitempty"`
}

func (obj MultiClusterCanary) GetRequeueAfter() time.Duration {
	return obj.Spec.Interval.Duration
}

func (obj MultiClusterCanary) GetCanaryNamespace() string {
	if obj.Spec.CanaryNamespace != "" {
		return obj.Spec.CanaryNamespace
	}
	return obj.Namespace
}

func (obj MultiClusterCanary) GetFailedRetriesThreshold() int {
	if obj.Spec.PromotionStrategy.FailedRetriesThreshold == nil {
		return 3
	}
	return *obj.Spec.PromotionStrategy.FailedRetriesThreshold
}

//+kubebuilder:object:root=true
//+kubebuilder:subresource:status

// MultiClusterCanary is the Schema for the multiclustercanaries API
type MultiClusterCanary struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   MultiClusterCanarySpec   `json:"spec,omitempty"`
	Status MultiClusterCanaryStatus `json:"status,omitempty"`
}

//+kubebuilder:object:root=true

// MultiClusterCanaryList contains a list of MultiClusterCanary
type MultiClusterCanaryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MultiClusterCanary `json:"items"`
}

func init() {
	SchemeBuilder.Register(&MultiClusterCanary{}, &MultiClusterCanaryList{})
}
