//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/fluxcd/flagger/pkg/apis/flagger/v1beta1"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryObjRef) DeepCopyInto(out *CanaryObjRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryObjRef.
func (in *CanaryObjRef) DeepCopy() *CanaryObjRef {
	if in == nil {
		return nil
	}
	out := new(CanaryObjRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanaryWebhookState) DeepCopyInto(out *CanaryWebhookState) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanaryWebhookState.
func (in *CanaryWebhookState) DeepCopy() *CanaryWebhookState {
	if in == nil {
		return nil
	}
	out := new(CanaryWebhookState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitopsCluster) DeepCopyInto(out *GitopsCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitopsCluster.
func (in *GitopsCluster) DeepCopy() *GitopsCluster {
	if in == nil {
		return nil
	}
	out := new(GitopsCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitopsCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitopsClusterList) DeepCopyInto(out *GitopsClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GitopsCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitopsClusterList.
func (in *GitopsClusterList) DeepCopy() *GitopsClusterList {
	if in == nil {
		return nil
	}
	out := new(GitopsClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GitopsClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitopsClusterSpec) DeepCopyInto(out *GitopsClusterSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitopsClusterSpec.
func (in *GitopsClusterSpec) DeepCopy() *GitopsClusterSpec {
	if in == nil {
		return nil
	}
	out := new(GitopsClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GitopsClusterStatus) DeepCopyInto(out *GitopsClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GitopsClusterStatus.
func (in *GitopsClusterStatus) DeepCopy() *GitopsClusterStatus {
	if in == nil {
		return nil
	}
	out := new(GitopsClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanary) DeepCopyInto(out *MultiClusterCanary) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanary.
func (in *MultiClusterCanary) DeepCopy() *MultiClusterCanary {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanary)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiClusterCanary) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryAnalysis) DeepCopyInto(out *MultiClusterCanaryAnalysis) {
	*out = *in
	in.CanaryAnalysis.DeepCopyInto(&out.CanaryAnalysis)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]MultiClusterCanaryAnalysisOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryAnalysis.
func (in *MultiClusterCanaryAnalysis) DeepCopy() *MultiClusterCanaryAnalysis {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryAnalysis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryAnalysisOverride) DeepCopyInto(out *MultiClusterCanaryAnalysisOverride) {
	*out = *in
	in.GitopsClusterSelector.DeepCopyInto(&out.GitopsClusterSelector)
	in.Analysis.DeepCopyInto(&out.Analysis)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryAnalysisOverride.
func (in *MultiClusterCanaryAnalysisOverride) DeepCopy() *MultiClusterCanaryAnalysisOverride {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryAnalysisOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryList) DeepCopyInto(out *MultiClusterCanaryList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MultiClusterCanary, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryList.
func (in *MultiClusterCanaryList) DeepCopy() *MultiClusterCanaryList {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MultiClusterCanaryList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryService) DeepCopyInto(out *MultiClusterCanaryService) {
	*out = *in
	in.CanaryService.DeepCopyInto(&out.CanaryService)
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make([]MultiClusterCanaryServiceOverride, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryService.
func (in *MultiClusterCanaryService) DeepCopy() *MultiClusterCanaryService {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryServiceOverride) DeepCopyInto(out *MultiClusterCanaryServiceOverride) {
	*out = *in
	in.GitopsClusterSelector.DeepCopyInto(&out.GitopsClusterSelector)
	in.Service.DeepCopyInto(&out.Service)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryServiceOverride.
func (in *MultiClusterCanaryServiceOverride) DeepCopy() *MultiClusterCanaryServiceOverride {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryServiceOverride)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanarySpec) DeepCopyInto(out *MultiClusterCanarySpec) {
	*out = *in
	in.GitopsClusterSelector.DeepCopyInto(&out.GitopsClusterSelector)
	out.TargetRef = in.TargetRef
	out.Interval = in.Interval
	if in.AutoscalerRef != nil {
		in, out := &in.AutoscalerRef, &out.AutoscalerRef
		*out = new(v1beta1.AutoscalerRefernce)
		(*in).DeepCopyInto(*out)
	}
	if in.IngressRef != nil {
		in, out := &in.IngressRef, &out.IngressRef
		*out = new(v1beta1.LocalObjectReference)
		**out = **in
	}
	if in.RouteRef != nil {
		in, out := &in.RouteRef, &out.RouteRef
		*out = new(v1beta1.LocalObjectReference)
		**out = **in
	}
	if in.UpstreamRef != nil {
		in, out := &in.UpstreamRef, &out.UpstreamRef
		*out = new(v1beta1.CrossNamespaceObjectReference)
		**out = **in
	}
	in.Service.DeepCopyInto(&out.Service)
	in.Analysis.DeepCopyInto(&out.Analysis)
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(v1.Duration)
		**out = **in
	}
	in.PromotionStrategy.DeepCopyInto(&out.PromotionStrategy)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanarySpec.
func (in *MultiClusterCanarySpec) DeepCopy() *MultiClusterCanarySpec {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanarySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MultiClusterCanaryStatus) DeepCopyInto(out *MultiClusterCanaryStatus) {
	*out = *in
	if in.Inevntory != nil {
		in, out := &in.Inevntory, &out.Inevntory
		*out = make([]CanaryObjRef, len(*in))
		copy(*out, *in)
	}
	if in.RolloutApprovedAt != nil {
		in, out := &in.RolloutApprovedAt, &out.RolloutApprovedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MultiClusterCanaryStatus.
func (in *MultiClusterCanaryStatus) DeepCopy() *MultiClusterCanaryStatus {
	if in == nil {
		return nil
	}
	out := new(MultiClusterCanaryStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PromotionStrategy) DeepCopyInto(out *PromotionStrategy) {
	*out = *in
	if in.FailedRetriesThreshold != nil {
		in, out := &in.FailedRetriesThreshold, &out.FailedRetriesThreshold
		*out = new(int)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PromotionStrategy.
func (in *PromotionStrategy) DeepCopy() *PromotionStrategy {
	if in == nil {
		return nil
	}
	out := new(PromotionStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretReference) DeepCopyInto(out *SecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretReference.
func (in *SecretReference) DeepCopy() *SecretReference {
	if in == nil {
		return nil
	}
	out := new(SecretReference)
	in.DeepCopyInto(out)
	return out
}
